export default function sitemap() {
  const baseUrl = 'https://www.snsconstructioninc.com';
  
  // Cleaned routes array without the "app/" prefix and without backslashes
  const routes = [
    "about-us/sns-construction/our-code-of-conduct",
    "about-us/sns-construction/our-history",
    "about-us/sns-construction/our-organization",
    "about-us/sns-construction/our-purpose-and-values",
    "about-us/sns-construction/quick-facts",
    "about-us/sns-construction/usa-leadership-team",
    "about-us/sns-construction-group/investors",
    "careers/openings",
    "careers",
    "careers/verification",
    "commercial-development",
    "commercial-offices",
    "construction/approach/community-investment",
    "construction/approach/delivery-methods",
    "construction/approach/environmental-health-safety",
    "construction/approach/ethics",
    "construction/approach/inclusion-diversity",
    "construction/approach/subcontractors-suppliers",
    "construction/expertise/emerging-technology",
    "construction/expertise/megaprojects",
    "construction/expertise/programmanagement",
    "construction/expertise/strategic-supply-chain",
    "construction/expertise/sustainability",
    "construction/transportation-infrastructure/airports",
    "construction/transportation-infrastructure/bridges",
    "construction/transportation-infrastructure/dams",
    "construction/transportation-infrastructure/equipment-for-sale",
    "construction/transportation-infrastructure/highways-roads",
    "construction/transportation-infrastructure/mining",
    "construction/transportation-infrastructure/ports-marine",
    "construction/transportation-infrastructure/resiliency",
    "construction/transportation-infrastructure/structural-steel",
    "construction/transportation-infrastructure/transit-rail",
    "construction/transportation-infrastructure/tunneling",
    "construction/transportation-infrastructure/underpinning-foundations",
    "construction/transportation-infrastructure/water-wastewater-systems",
    "cookie",
    "cultural-religious",
    "data-centers",
    "government-municipal",
    "healthcare",
    "higher-education",
    "hotels",
    "k-12-education",
    "media",
    "multi-family",
    "offer-verification",
    "parks-waterfront",
    "policy",
    "science-technology",
    "sports",
    "terms-of-use",
    "verification",
    "where-we-work"
  ];
  
  return [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    ...routes.map(route => ({
      url: `${baseUrl}/${route}`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    }))
  ];
}
